# Generated by Django 5.2.2 on 2025-06-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperatura", models.FloatField()),
                ("vibracao", models.FloatField()),
                ("corrente", models.FloatField()),
                ("velocidade", models.IntegerField()),
                ("posicao", models.IntegerField()),
                ("pressao", models.FloatField()),
                ("nivel", models.IntegerField()),
                ("qualidade_ar", models.IntegerField()),
                ("umidade", models.FloatField()),
                ("tensao", models.FloatField()),
                ("fumaca", models.IntegerField()),
            ],
        ),
    ]
