# Generated by Django 5.2.2 on 2025-06-07 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_sensor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
